"""业务系统使用的统一领域常量。

本模块集中维护部署类型、排程类型、订单类型、工序状态、任务状态和版本状态。
"""

from __future__ import annotations

from typing import Final


# 算法排程工艺
SCHEDULE_TYPE_MACHINING: Final = "machining"
SCHEDULE_TYPE_HEAT_TREATMENT: Final = "heat_treatment"
SCHEDULE_TYPE_ASSEMBLY: Final = "assembly"
SCHEDULE_TYPES: Final = frozenset(
    {SCHEDULE_TYPE_MACHINING, SCHEDULE_TYPE_HEAT_TREATMENT, SCHEDULE_TYPE_ASSEMBLY}
)
SCHEDULE_TYPE_CHOICES: Final = (
    SCHEDULE_TYPE_MACHINING,
    SCHEDULE_TYPE_HEAT_TREATMENT,
    SCHEDULE_TYPE_ASSEMBLY,
)

# 排程运行模式
SCHEDULE_MODE_STATIC: Final = "static"
SCHEDULE_MODE_DYNAMIC: Final = "dynamic"
SCHEDULE_MODE_LOCAL: Final = "local"
SCHEDULE_MODES: Final = frozenset(
    {SCHEDULE_MODE_STATIC, SCHEDULE_MODE_DYNAMIC, SCHEDULE_MODE_LOCAL}
)

# 订单业务类型
ORDER_BUSINESS_TYPE_MACHINING: Final = "MACHINING"
ORDER_BUSINESS_TYPE_HEAT_TREAT: Final = "HEAT_TREAT"
ORDER_BUSINESS_TYPE_SURFACE_TREAT: Final = "SURFACE_TREAT"
ORDER_BUSINESS_TYPE_ASSEMBLY: Final = "ASSEMBLY"
ORDER_BUSINESS_TYPES: Final = frozenset(
    {
        ORDER_BUSINESS_TYPE_MACHINING,
        ORDER_BUSINESS_TYPE_HEAT_TREAT,
        ORDER_BUSINESS_TYPE_SURFACE_TREAT,
        ORDER_BUSINESS_TYPE_ASSEMBLY,
    }
)
SCHEDULE_ORDER_BUSINESS_TYPES: Final = {
    SCHEDULE_TYPE_MACHINING: frozenset({ORDER_BUSINESS_TYPE_MACHINING}),
    SCHEDULE_TYPE_HEAT_TREATMENT: frozenset(
        {ORDER_BUSINESS_TYPE_HEAT_TREAT, ORDER_BUSINESS_TYPE_SURFACE_TREAT}
    ),
    SCHEDULE_TYPE_ASSEMBLY: frozenset({ORDER_BUSINESS_TYPE_ASSEMBLY}),
}

# 业务系统部署类型
DEPLOYMENT_PROCESS_TYPE_MACHINING: Final = "MACHINING"
DEPLOYMENT_PROCESS_TYPE_HEAT_TREATMENT: Final = "HEAT_TREATMENT"
DEPLOYMENT_PROCESS_TYPE_ASSEMBLY: Final = "ASSEMBLY"
DEPLOYMENT_PROCESS_TYPE_DEBUG: Final = "DEBUG"
DEPLOYMENT_PROCESS_TYPES: Final = frozenset(
    {
        DEPLOYMENT_PROCESS_TYPE_MACHINING,
        DEPLOYMENT_PROCESS_TYPE_HEAT_TREATMENT,
        DEPLOYMENT_PROCESS_TYPE_ASSEMBLY,
        DEPLOYMENT_PROCESS_TYPE_DEBUG,
    }
)
DEPLOYMENT_PROCESS_TYPE_CHOICES: Final = (
    DEPLOYMENT_PROCESS_TYPE_MACHINING,
    DEPLOYMENT_PROCESS_TYPE_HEAT_TREATMENT,
    DEPLOYMENT_PROCESS_TYPE_ASSEMBLY,
    DEPLOYMENT_PROCESS_TYPE_DEBUG,
)
DEPLOYMENT_SCHEDULE_TYPES: Final = {
    DEPLOYMENT_PROCESS_TYPE_MACHINING: SCHEDULE_TYPE_MACHINING,
    DEPLOYMENT_PROCESS_TYPE_HEAT_TREATMENT: SCHEDULE_TYPE_HEAT_TREATMENT,
    DEPLOYMENT_PROCESS_TYPE_ASSEMBLY: SCHEDULE_TYPE_ASSEMBLY,
}
DEFAULT_SYSTEM_NAMES: Final = {
    DEPLOYMENT_PROCESS_TYPE_MACHINING: "机加智能排程",
    DEPLOYMENT_PROCESS_TYPE_HEAT_TREATMENT: "热表智能排程",
    DEPLOYMENT_PROCESS_TYPE_ASSEMBLY: "装配智能排程",
    DEPLOYMENT_PROCESS_TYPE_DEBUG: "调试智能排程",
}
SYSTEM_CONFIGURATION_ID: Final = "BUSINESS_UNIT"

# 资源组类型
RESOURCE_GROUP_TYPE_MACHINING: Final = ORDER_BUSINESS_TYPE_MACHINING
RESOURCE_GROUP_TYPE_HEAT_TREAT: Final = ORDER_BUSINESS_TYPE_HEAT_TREAT
RESOURCE_GROUP_TYPE_SURFACE_TREAT: Final = ORDER_BUSINESS_TYPE_SURFACE_TREAT
RESOURCE_GROUP_TYPE_ASSEMBLY: Final = ORDER_BUSINESS_TYPE_ASSEMBLY
RESOURCE_GROUP_TYPE_INSPECTION: Final = "INSPECTION"
RESOURCE_GROUP_TYPE_MANUAL: Final = "MANUAL"
RESOURCE_GROUP_SCHEDULE_TYPES: Final = {
    RESOURCE_GROUP_TYPE_MACHINING: SCHEDULE_TYPE_MACHINING,
    RESOURCE_GROUP_TYPE_HEAT_TREAT: SCHEDULE_TYPE_HEAT_TREATMENT,
    RESOURCE_GROUP_TYPE_SURFACE_TREAT: SCHEDULE_TYPE_HEAT_TREATMENT,
    RESOURCE_GROUP_TYPE_ASSEMBLY: SCHEDULE_TYPE_ASSEMBLY,
}

# 工序状态
PROCESS_STATUS_PENDING: Final = "PENDING"
PROCESS_STATUS_SCHEDULED: Final = "SCHEDULED"
PROCESS_STATUS_CONFIRMED: Final = "CONFIRMED"
PROCESS_STATUS_IN_PROGRESS: Final = "IN_PROGRESS"
PROCESS_STATUS_COMPLETED: Final = "COMPLETED"
PROCESS_STATUS_PAUSED: Final = "PAUSED"
PROCESS_STATUS_CANCELLED: Final = "CANCELLED"
PROCESS_TERMINAL_STATUSES: Final = frozenset(
    {PROCESS_STATUS_COMPLETED, PROCESS_STATUS_CANCELLED}
)
PROCESS_PUBLISHED_STATUSES: Final = frozenset(
    {
        PROCESS_STATUS_IN_PROGRESS,
        PROCESS_STATUS_PAUSED,
        PROCESS_STATUS_COMPLETED,
        PROCESS_STATUS_CANCELLED,
    }
)
PROCESS_RUNTIME_LOCK_STATUSES: Final = frozenset(
    {PROCESS_STATUS_IN_PROGRESS, PROCESS_STATUS_PAUSED}
)
PROCESS_MANUAL_ADJUSTMENT_BLOCKED_STATUSES: Final = frozenset(
    {
        PROCESS_STATUS_IN_PROGRESS,
        PROCESS_STATUS_PAUSED,
        PROCESS_STATUS_COMPLETED,
        PROCESS_STATUS_CANCELLED,
    }
)

# 排程任务状态
TASK_STATUS_QUEUED: Final = "QUEUED"
TASK_STATUS_RUNNING: Final = "RUNNING"
TASK_STATUS_SUCCEEDED: Final = "SUCCEEDED"
TASK_STATUS_FAILED: Final = "FAILED"
TASK_RUNNABLE_STATUSES: Final = frozenset({TASK_STATUS_QUEUED, TASK_STATUS_FAILED})
TASK_ACTIVE_STATUSES: Final = frozenset({TASK_STATUS_QUEUED, TASK_STATUS_RUNNING})

# 计划版本状态与审批决定
VERSION_STATUS_DRAFT: Final = "DRAFT"
VERSION_STATUS_APPROVED: Final = "APPROVED"
VERSION_STATUS_REJECTED: Final = "REJECTED"
VERSION_STATUS_PUBLISHED: Final = "PUBLISHED"
VERSION_STATUS_SUPERSEDED: Final = "SUPERSEDED"
VERSION_REVIEW_DECISIONS: Final = frozenset(
    {VERSION_STATUS_APPROVED, VERSION_STATUS_REJECTED}
)
VERSION_STATUS_CHOICES: Final = (
    VERSION_STATUS_DRAFT,
    VERSION_STATUS_APPROVED,
    VERSION_STATUS_PUBLISHED,
    VERSION_STATUS_SUPERSEDED,
    VERSION_STATUS_REJECTED,
)

# 用户角色
USER_ROLE_ADMIN: Final = "admin"
USER_ROLE_PLANNER: Final = "planner"
USER_ROLE_APPROVER: Final = "approver"
USER_ROLE_VIEWER: Final = "viewer"
USER_ROLE_CHOICES: Final = (
    USER_ROLE_ADMIN,
    USER_ROLE_PLANNER,
    USER_ROLE_APPROVER,
    USER_ROLE_VIEWER,
)

# 主数据与排程展示状态
RECORD_STATUS_ACTIVE: Final = "ACTIVE"
SCHEDULE_RECORD_STATUS_EFFECTIVE: Final = "EFFECTIVE"
SCHEDULE_RECORD_STATUS_HISTORICAL: Final = "HISTORICAL"
SCHEDULE_RECORD_STATUS_UNSCHEDULED: Final = "UNSCHEDULED"
SCHEDULE_RECORD_STATUS_UNKNOWN: Final = "UNKNOWN"

# 版本差异类型
CHANGE_TYPE_ADDED: Final = "ADDED"
CHANGE_TYPE_REMOVED: Final = "REMOVED"
CHANGE_TYPE_MODIFIED: Final = "MODIFIED"

# 接口与默认业务值
HEALTH_STATUS_UP: Final = "UP"
HEALTH_STATUS_DOWN: Final = "DOWN"
DISPATCH_RULE_DELIVERY: Final = "DELIVERY"

# 局部调整策略
ADJUSTMENT_STRATEGY_MOVE_ONLY: Final = "move_only"
ADJUSTMENT_STRATEGY_SYNC_DOWNSTREAM: Final = "sync_downstream"
ADJUSTMENT_STRATEGY_LOCAL_RESCHEDULE: Final = "local_reschedule"
ADJUSTMENT_STRATEGIES: Final = frozenset(
    {
        ADJUSTMENT_STRATEGY_MOVE_ONLY,
        ADJUSTMENT_STRATEGY_SYNC_DOWNSTREAM,
        ADJUSTMENT_STRATEGY_LOCAL_RESCHEDULE,
    }
)

# 局部调整校验编码
ADJUSTMENT_CODE_PROCESS_CONSTRAINT: Final = "PROCESS_CONSTRAINT"
ADJUSTMENT_CODE_MANUAL_LOCK: Final = "MANUAL_LOCK"
ADJUSTMENT_CODE_DURATION_VALID: Final = "DURATION_VALID"
ADJUSTMENT_CODE_PAST_TIME: Final = "PAST_TIME"
ADJUSTMENT_CODE_PREDECESSOR_UNFINISHED: Final = "PREDECESSOR_UNFINISHED"
ADJUSTMENT_CODE_PREDECESSOR_LOCKED: Final = "PREDECESSOR_LOCKED"
ADJUSTMENT_CODE_PREDECESSOR_VALID: Final = "PREDECESSOR_VALID"
ADJUSTMENT_CODE_MACHINE_LOCK_CONFLICT: Final = "MACHINE_LOCK_CONFLICT"
ADJUSTMENT_CODE_MACHINE_CONFLICT: Final = "MACHINE_CONFLICT"
ADJUSTMENT_CODE_WORKER_LOCK_CONFLICT: Final = "WORKER_LOCK_CONFLICT"
ADJUSTMENT_CODE_WORKER_CONFLICT: Final = "WORKER_CONFLICT"
ADJUSTMENT_CODE_DOWNSTREAM_LOCK_CONFLICT: Final = "DOWNSTREAM_LOCK_CONFLICT"
ADJUSTMENT_CODE_TOOLING_CHANGE: Final = "TOOLING_CHANGE"
ADJUSTMENT_CODE_BASE_CHANGEOVER: Final = "BASE_CHANGEOVER"
ADJUSTMENT_CODE_DUE_DATE_DELAY: Final = "DUE_DATE_DELAY"

# 算法约束编码
CONSTRAINT_CODE_TIME_RANGE_INVALID: Final = "TIME_RANGE_INVALID"
CONSTRAINT_CODE_PROCESS_DURATION_SHORTAGE: Final = "PROCESS_DURATION_SHORTAGE"
CONSTRAINT_CODE_RESOURCE_CALENDAR: Final = "RESOURCE_CALENDAR"
CONSTRAINT_CODE_RESOURCE_CALENDAR_NO_WINDOW: Final = "RESOURCE_CALENDAR_NO_WINDOW"

# 编号前缀
SCHEDULE_TASK_ID_PREFIX: Final = "SCH-"
SCHEDULE_VERSION_ID_PREFIX: Final = "PLAN-"
VERSION_AUDIT_ACTION_PREFIX: Final = "VERSION_"

# 审计动作
AUDIT_ACTION_USER_LOGIN: Final = "USER_LOGIN"
AUDIT_ACTION_PASSWORD_CHANGED: Final = "PASSWORD_CHANGED"
AUDIT_ACTION_USER_CREATED: Final = "USER_CREATED"
AUDIT_ACTION_USER_UPDATED: Final = "USER_UPDATED"
AUDIT_ACTION_MASTER_DATA_IMPORTED: Final = "MASTER_DATA_IMPORTED"
AUDIT_ACTION_MASTER_DATA_BATCH_IMPORTED: Final = "MASTER_DATA_BATCH_IMPORTED"
AUDIT_ACTION_MASTER_DATA_SAVED: Final = "MASTER_DATA_SAVED"
AUDIT_ACTION_MASTER_DATA_DELETED: Final = "MASTER_DATA_DELETED"
AUDIT_ACTION_PROCESS_MANUALLY_LOCKED: Final = "PROCESS_MANUALLY_LOCKED"
AUDIT_ACTION_PROCESS_MANUALLY_UNLOCKED: Final = "PROCESS_MANUALLY_UNLOCKED"
AUDIT_ACTION_PROCESS_ADJUSTMENT_CONFIRMED: Final = "PROCESS_ADJUSTMENT_CONFIRMED"
AUDIT_ACTION_TASK_CREATED: Final = "TASK_CREATED"
AUDIT_ACTION_TASK_RETRIED: Final = "TASK_RETRIED"
AUDIT_ACTION_TASK_FAILED: Final = "TASK_FAILED"
AUDIT_ACTION_TASK_SUCCEEDED: Final = "TASK_SUCCEEDED"
AUDIT_ACTION_VERSION_PUBLISHED: Final = "VERSION_PUBLISHED"
AUDIT_ACTION_SYSTEM_CONFIGURATION_UPDATED: Final = "SYSTEM_CONFIGURATION_UPDATED"
AUDIT_ACTION_DEMO_DATA_INITIALIZED: Final = "DEMO_DATA_INITIALIZED"
